config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/dashboard' => 'home#index', as: :dashboard

  resources :projects do
    member do
      get "customer_qoute"
      get "send_quotation"
      post "rfq"
      post "create_order"
    end
    collection do
      post 'request_supplier_qoute'
      get 'search'

    end
  end

  resources :companies do
    collection do
      get "search"
    end
  end
  resources :products do
    collection do
      get 'load_form'
      get 'load_addons'
      get 'prefill_data'
      get "artwork_children"
    end
  end
  resources :orders do
    collection do
      get 'tracking'
      get 'status'
      post 'create_order_tracking'
      get 'search'
    end
    member do
      get "enter_shipment_details"
    end
  end

  get '/users/new'=>"users#new", as: :new_users
  post '/users/create'=>"users#create", as: :users
  get '/project-managers'=>"users#index", as: :project_managers
  delete 'users/:id', to: "users#destroy", as: :destroy_user
  get "users/search", to: "users#search"
  post 'create_request_quote', to: "companies#create_request_quote", as: :create_request_quote

  get '/product_ajax_load', to: 'projects#product_ajax_load'
  get '/quote_request/:id', to: "prices#new_supplier_price", as: :quote_request
  post '/prices', to: "prices#create", as: :prices
  patch '/prices/:id', to: "prices#update", as: :price

end

app/models/products/artwork.rb
class Products::Artwork < Product


  #field :type
  field :title
  field :width    #image width
  field :height   #image height
  field :supplier_id
  field :moulding_company_id
  field :frame_id
  field :image_id
  field :board_option
  field :acrylic_thickness
  field :matting
  field :mat_size
  field :mat_special_instructions
  field :glazing
  field :glazing_special_instructions
  field :glass_width
  field :glass_height
  field :glass_united_inches
  field :category
  field :frame_size
  field :overall_width
  field :overall_height

   #need image source field source
  mount_uploader :source, SourceUploader

  def field_names
    %w(title artist width height source)
  end

  def addons
    %w(frame)
  end

  def image=(arg)
    image = Image.create(arg)
    unless image.errors.any?
      self.image_id = image.id
      self.title = image.title
      self.width = image.width
      self.height = image.height
    else
      errors.add(:image, product.errors.full_messages.join(', '))
    end
  end

  def supplier=(arg)
    supplier= Supplier.create(arg)
    unless supplier.errors.any?
      self.supplier_id = supplier.id
    else
      errors.add(:supplier, product.errors.full_messages.join(', '))
    end
  end

  def moulding_company=(arg)
    company = MouldingCompany.create(arg)
    unless company.errors.any?
      self.moulding_company_id = company.id
    else
      errors.add(:moulding_company, product.errors.full_messages.join(', '))
    end
  end

  def frame=(arg)
    frame = Frame.create(arg)
    unless frame.errors.any?
      self.frame_id = frame.id
      self.category = frame.category
      self.frame_size = frame.size
    else
      errors.add(:frame, product.errors.full_messages.join(', '))
    end
  end

  def new_board_option=(arg)
    self.board_option = arg[:name]
  end

  def new_acrylic_thickness=(arg)
    self.acrylic_thickness = arg[:name]
  end

  def new_matting=(arg)
    self.matting = arg[:name]
  end

  def supplier
    Supplier.find(supplier_id)
  end

  def moulding_company
    MouldingCompany.find(moulding_company_id)
  end

  def frame
    Frame.find(frame_id)
  end

  def image
    Image.find(image_id)

  end

  def self.artine_item_numbers
    Price.in(product_id: Artwork.pluck(:id)).pluck(:artline_item_number)
  end


  def details
     "Publisher: #{supplier.name}\n Image: #{image["title"]}  Artist: #{image.artist}\n Title: #{title} \n Width: #{width}\n Height: #{height}"
  end

  def glass_united_inches
    self["glass_width"].to_i + self["glass_height"].to_i
  end

end

app/views/products/forms/artwork/_acrylic.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Acrylic"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  = render "products/forms/artwork/similar_fields", f: f
  .row
    .col-md-3.mbtm15
      - if @product.persisted?
        - if ["1/4","1/2"].include?@product.acrylic_thickness
          Acrylic Thickness
          = f.select :acrylic_thickness, options_for_select(["1/4","1/2","add"],@product.acrylic_thickness),{prompt: "Acrylic Thickness"} , class: "form-control", onchange:"add_field(this)",data:{name: 'acrylic_thickness'},required: true
        - else
          Acrylic Thickness
          %input.form-control{:name => "product[new_acrylic_thickness][name]",value: @product.acrylic_thickness , required: "required", type: "text"}
      - else
        Acrylic Thickness
        = f.select :acrylic_thickness, options_for_select(["1/4","1/2","add"]),{prompt: "Acrylic Thickness"} , class: "form-control", onchange:"add_field(this)",data:{name: 'acrylic_thickness'},required: true
  .row
    .col-md-3.mbtm15.acrylic_thickness

  = f.submit nil, class: "btn btn-success mbtm15"

app/views/products/forms/artwork/_aluminum.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Aluminum"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  = render "products/forms/artwork/similar_fields", f: f
  = f.submit nil, class: "btn btn-success mbtm15"

app/views/products/forms/artwork/_colorboard.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Colorboard"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  = render "products/forms/artwork/similar_fields", f: f
  .row
    .col-md-3.mbtm15
      - if @product.persisted?
        - if ["Lite Board","Float Board","Boxed Board","Doublelite"].include?@product.board_option
          Board Options
          = f.select :acrylic_thickness, options_for_select(["Lite Board","Float Board","Boxed Board","Doublelite","add"],@product.board_option),{prompt: "Board Options"} , class: "form-control", onchange:"add_field(this)",data:{name: 'board_option'},required: true
        - else
          Board Options
          %input.form-control{:name => "product[new_board_option][name]",value: @product.board_option , required: "required", type: "text"}
      - else
        Board Options
        = f.select :acrylic_thickness, options_for_select(["Lite Board","Float Board","Boxed Board","Doublelite","add"]),{prompt: "Board Options"} , class: "form-control", onchange:"add_field(this)",data:{name: 'board_option'},required: true
  .row
    .col-md-3.mbtm15.board_option

  = f.submit nil, class: "btn btn-success mbtm15"

app/views/products/forms/artwork/_framed_art.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Framed_Art"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  .row
    .col-md-3.mbtm15
      Publisher
      = f.select :supplier_id, options_for_select(Supplier.all.map{|s|[s.name, s.id]}.push('add'),@product.persisted? ? @product.supplier.id : nil),{:prompt => "Publisher"} , class:"form-control", onchange:"new_item(this)", data:{name: 'Supplier'},required: true
  .supplier
  .row
    .col-md-3.mbtm15
      Image
      = f.select :image_id, options_for_select(Image.pluck(:title,:id).push('add'),@product.persisted? ? @product.image.id : nil),{:prompt => "Image"}, class: "form-control", onchange:"new_item(this)", data:{name: 'Image', addon:true},required: true
  .image
  .replaceable
    .row
      .col-md-3.mbtm15
        Title
        = f.text_field :title, value: @product.title, class: "form-control",required: true
    .row
      .col-md-3.mbtm15
        Width
        = f.number_field :width, value: @product.width,min:1, class: "form-control",required: true, onchange:"image_width(this)"
      .col-md-3.mbtm15
        Height
        = f.number_field :height, value: @product.height,min:1, class: "form-control",required: true, onchange:"image_height(this)"
  .row
    .col-md-3.mbtm15
      %label
      - if @product.persisted?
        - if ["Single", "Double","None","add"].include?@product.matting
          Matting
          = f.select :matting, options_for_select(["Single", "Double","None","add"],@product.matting),{prompt: "Matting"} , class: "form-control", onchange:"add_field(this)",data:{name: 'matting'},required: true
        - else
          Matting
          %input.form-control{:name => "product[new_matting][name]",value: @product.matting , required: "required", type: "text"}
      - else
        Matting
        = f.select :matting, options_for_select(["Single", "Double","None","add"],@product.matting),{prompt: "Matting"} , class: "form-control", onchange:"add_field(this)",data:{name: 'matting'},required: true
    .col-md-3.mbtm15
      Matting Size
      = f.text_field :mat_size, value: @product.mat_size? ? @product.mat_size : 1 ,min:1, class: "form-control",required: true, onchange:"mat_size(this)"
  .row
    .col-md-3.mbtm15.matting
  .row
    .col-md-3.mbtm15.txt_area
      Matting special instructions
      = f.text_area :mat_special_instructions, value: @product.mat_special_instructions,class:"form-control"
  .row
    .col-md-3.mbtm15
      Glazing
      = f.select :glazing, options_for_select(["Glass", "Plexie","None"],@product.glazing),{prompt: "Glazing"} , class: "form-control", required: true
  .row
    .col-md-3.mbtm15.txt_area
      Glazing special instructions
      = f.text_area :glazing_special_instructions, value: @product.glazing_special_instructions,class:"form-control"
  .row
    .col-md-3.mbtm15
      Glass width
      = f.number_field :glass_width, value: @product.glass_width? ? @product.glass_width : 2,min:1, class: "form-control",required: true, onchange:"glass_width_artwork(this)"
    .col-md-3.mbtm15
      Glass height
      = f.number_field :glass_height, value: @product.glass_height? ? @product.glass_height : 2,min:1, class: "form-control",required: true, onchange:"glass_height_artwork(this)"
  .row
    .col-md-3.mbtm15
      Glass united inches
      = f.number_field :glass_united_inches, value: @product.glass_united_inches? ? @product.glass_united_inches : 4,min:1, class: "form-control",required: true,readonly: true
  .row
    .col-md-3.mbtm15
      Moulding company
      = f.select :moulding_company_id, options_for_select(MouldingCompany.all.map{|m|[m.name, m.id]}.push('add'),@product.moulding_company_id),{:prompt => "Moulding Company"} , class:"form-control", onchange:"new_item(this)", data:{name: 'MouldingCompany'},required: true
  .mouldingcompany
  .row
    .col-md-3.mbtm15
      Frame
      = f.select :frame_id, options_for_select(Frame.all.map{|f| [f["finish"],f["id"]]}.push('add'),@product.frame_id),{:prompt => "Frame"} , class:"form-control", onchange:"new_item(this)", data:{name: 'Frame', addon: true},required: true
  .frame
  .row.replaceable
    .col-md-3.mbtm15
      Frame category
      = f.text_field :category, value: @product.category, class: "form-control",required: true,readonly: true
    .col-md-3.mbtm15
      Frame size
      = f.number_field :frame_size, value: @product.frame_size? ? @product.frame_size : 1,min:1, class: "form-control",required: true, onchange:"frame_size(this)",readonly: true
  .row
    .col-md-3.mbtm15
      Overall width
      = f.number_field :overall_width, value: @product.overall_width? ? @product.overall_width : 4,min:1, class: "form-control",required: true, onchange:"overall_width(this)"
    .col-md-3.mbtm15
      Overall height
      = f.number_field :overall_height, value: @product.overall_height? ? @product.overall_height : 4,min:1, class: "form-control",required: true, onchange:"overall_height(this)"


  = f.submit nil, class: "btn btn-success mbtm15"

app/views/products/forms/artwork/_other.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Other"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  = render "products/forms/artwork/similar_fields", f: f
  .row
    .col-md-3.mbtm15.txt_area
      Description
      = f.text_area "description", value: @product["description"], class: "form-control",required: true
  = f.submit nil, class: "btn btn-success mbtm15"

app/views/products/forms/artwork/_similar_fields.html.haml
.row
  .col-md-3.mbtm15
    Publisher
    = f.select :supplier_id, options_for_select(Supplier.all.map{|s|[s.name, s.id]}.push('add'),@product.persisted? ? @product.supplier.id : nil),{:prompt => "Publisher"} , class:"form-control", onchange:"new_item(this)", data:{name: 'Supplier'},required: true
.supplier
.row
  .col-md-3.mbtm15
    Image
    = f.select :image_id, options_for_select(Image.pluck(:title,:id).push('add'),@product.persisted? ? @product.image.id : nil),{:prompt => "Image"}, class: "form-control", onchange:"new_item(this)", data:{name: 'Image', addon:true},required: true
.image
.replaceable
  .row
    .col-md-3.mbtm15
      Title
      = f.text_field :title, value: @product.title, class: "form-control",required: true
  .row
    .col-md-3.mbtm15
      Width
      = f.number_field :width, value: @product.width,min:1, class: "form-control",required: true
    .col-md-3.mbtm15
      Height
      = f.number_field :height, value: @product.height,min:1, class: "form-control",required: true

app/views/products/forms/artwork/_vinyl.html.haml
= form_for @product, as: :product, url:( @product.new_record? ? products_path(@product) : product_path(@product)) do |f|
  = hidden_field_tag :item_type, @product.class
  = hidden_field_tag "product[artwork_type]", "Vinyl"
  - if @product.errors.present?
    #error_explanation
      %h2 #{@product.errors.count} error prohibited this user from being saved:
      %ul
        - @product.errors.full_messages.each do |error|
          %li
            = "#{error}"
  = render "products/forms/artwork/similar_fields", f: f
  = f.submit nil, class: "btn btn-success mbtm15"