config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/dashboard' => 'home#index', as: :dashboard

  resources :projects do
    member do
      get "customer_qoute"
      get "send_quotation"
      post "rfq"
      post "create_order"
    end
    collection do
      post 'request_supplier_qoute'
      get 'search'

    end
  end

  resources :companies do
    collection do
      get "search"
    end
  end
  resources :products do
    collection do
      get 'load_form'
      get 'load_addons'
      get 'prefill_data'
      get "artwork_children"
    end
  end
  resources :orders do
    collection do
      get 'tracking'
      get 'status'
      post 'create_order_tracking'
      get 'search'
    end
    member do
      get "enter_shipment_details"
    end
  end

  get '/users/new'=>"users#new", as: :new_users
  post '/users/create'=>"users#create", as: :users
  get '/project-managers'=>"users#index", as: :project_managers
  delete 'users/:id', to: "users#destroy", as: :destroy_user
  get "users/search", to: "users#search"
  post 'create_request_quote', to: "companies#create_request_quote", as: :create_request_quote

  get '/product_ajax_load', to: 'projects#product_ajax_load'
  get '/quote_request/:id', to: "prices#new_supplier_price", as: :quote_request
  post '/prices', to: "prices#create", as: :prices
  patch '/prices/:id', to: "prices#update", as: :price

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Paranoia
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects

  ROLES = %w[super_admin project_manager]

  ## Database authenticatable
  field :fname,         type: String, default: ""
  field :lname,              type: String, default: ""
  field :phone,              type: String
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  ##custom
  field :roles, type:Array, default: ['project_manager']

  index({"fname" => "text","lname" => "text"},{background: true})

  def is?(role)
    respond_to?(:roles) and roles.to_a.include?(role.to_s)
  end

  def full_name
    "#{fname} #{lname}".strip
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
     @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
   @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.any?
      render 'new'
    else
      redirect_to project_managers_path, alert: "Project Manager Successfully Created"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User successfully deleted"
    redirect_to project_managers_path
  end

  def search
    @users = User.where("$text"=>{"$search"=>params["key"]}).paginate(page: params[:page], per_page: 5)
    render 'index'
  end

  private

  def user_params
    params.require(:user).permit(params[:user].keys)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
%section#main-content.cus
  %section.wrapper
    %div.serch_bg
      #top_menu.nav.search-row.txt-clr
        %ul.nav.top-menu
          %li
            = link_to "Create New Project Manager", new_users_path,class:'btn'
          %li
            = form_tag(users_search_path, method: "get") do
              %input.form-control{placeholder: "Search with fname or lname", type: "text", name: "key"}
    %section.panel
      %header.panel-heading.no-border
        Project manager's
      %table.table.table-bordered
        %thead
          %tr
            %th #
            %th First Name
            %th Last Name
            %th Email
            %th Action
        %tbody
        - @users.each_with_index do |user,index|
          %tr
            %td
              #{index+1}
            %td
              #{user.fname}
            %td
              #{user.lname}
            %td
              #{user.email}
            %td
              - unless user.is?(:super_admin)
                .btn-group
                  = link_to("", destroy_user_path(user.id),method: :delete , class: "btn glyphicon glyphicon-trash red" )
      .flickr_pagination
        = will_paginate @users

app/views/users/new.html.haml
%section#main-content
  %section.wrapper
    %h2 Create Project Manager
    %section.panel
      %div.panel-body.ptop35
        = form_for(@user, url: users_path) do |f|
          - if @user.errors.present?
            #error_explanation
              %h2 #{@user.errors.count} error prohibited this user from being saved:
              %ul
                - @user.errors.full_messages.each do |k|
                  %li
                    = "#{k}"
          %div.col-md-12
            %div.row.mbtm15
              %div.col-sm-3
                = f.text_field :fname, autofocus: true,class: "form-control",placeholder: "First Name", required: true
              %div.col-sm-3
                = f.text_field :lname, autofocus: true,class: "form-control",placeholder: "Last Name", required: true
            %div.row.mbtm15
              %div.col-sm-3
                = f.telephone_field :phone,class: "form-control",placeholder: "Phone", required: true
              %div.col-sm-3
                = f.email_field :email, autofocus: true,class: "form-control",placeholder: "Email", required: true
            %div.row.mbtm15
              %div.col-sm-3
                - if @validatable
                  %em
                    (#{@minimum_password_length} characters minimum)
                = f.password_field :password, autocomplete: "off",class: "form-control",placeholder: "Password", required: true
              %div.col-sm-3
                = f.password_field :password_confirmation, autocomplete: "off",class: "form-control",placeholder: "Password Confirmation", required: true
          %div.col-md-12
            .actions
              = f.submit "Create",class: "btn btn-primary"