config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/dashboard' => 'home#index', as: :dashboard

  resources :projects do
    member do
      get "customer_qoute"
      get "send_quotation"
      post "rfq"
      post "create_order"
    end
    collection do
      post 'request_supplier_qoute'
      get 'search'

    end
  end

  resources :companies do
    collection do
      get "search"
    end
  end
  resources :products do
    collection do
      get 'load_form'
      get 'load_addons'
      get 'prefill_data'
      get "artwork_children"
    end
  end
  resources :orders do
    collection do
      get 'tracking'
      get 'status'
      post 'create_order_tracking'
      get 'search'
    end
    member do
      get "enter_shipment_details"
    end
  end

  get '/users/new'=>"users#new", as: :new_users
  post '/users/create'=>"users#create", as: :users
  get '/project-managers'=>"users#index", as: :project_managers
  delete 'users/:id', to: "users#destroy", as: :destroy_user
  get "users/search", to: "users#search"
  post 'create_request_quote', to: "companies#create_request_quote", as: :create_request_quote

  get '/product_ajax_load', to: 'projects#product_ajax_load'
  get '/quote_request/:id', to: "prices#new_supplier_price", as: :quote_request
  post '/prices', to: "prices#create", as: :prices
  patch '/prices/:id', to: "prices#update", as: :price

end

app/models/companies/client.rb
class Companies::Client < Company



end

app/models/companies/moulding_company.rb
class Companies::MouldingCompany < Company

end

app/models/companies/supplier.rb
class Companies::Supplier < Company

  field :number
 # field :name


  has_many :prices
  has_many :request_quotes

  before_validation :assign_supperier_number

  def assign_supperier_number
    self.number ||= generate_number
  end

  def generate_number
    charset = ('A'..'Z').to_a+(1..9).to_a
    tk =  "SP#{(0...4).map{ charset.to_a[rand(charset.size)] }.join}"
    loop do
      break unless Companies::Supplier.where(number:/^#{tk}$/i).exists?
      tk =  "SP#{(0...4).map{ charset.to_a[rand(charset.size)] }.join}"
    end
    tk
  end

end

app/models/company.rb
class Company
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic

  field :name
  field :attention, type: Array
  field :email

  index({"name" => "text"},{background: true})


  before_save do
    self.attention = attention.reject(&:blank?).uniq
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companys = Company.order_by(created_at: "desc").paginate(page: params[:page], per_page: 5)
  end

  def new
    respond_to do |format|
      format.html
      format.js { render partial: 'form', locals:{_type: params[:_type]}}
    end
  end

  def create
    @company = eval(params[:_type]).create(company_params)
    if @company.save
     # redirect_to companies_url
      respond_to do |format|
        format.html { redirect_to companies_url }
        format.json {render json: {message: "Successfully created"} }
      end
    else
      render :new
    end
  end

  def show
    if @company
      respond_to do |format|
        format.html
        format.json {render json: @company }
      end
    else
      render nothing: true, status:404
    end
  end

  def edit

  end

  def update
    if @company.update(company_params)
      flash[:notice] = "Successfully Updated"
      redirect_to companies_url
    else
      flash[:notice] = "not updated"
      render :edit
    end
  end

  def destroy
    if @company.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to companies_url
    else
      flash[:notice] = "Record Not found"
      redirect_to companies_url
    end
  end

  def create_request_quote
    params[:request_quote][:supplier_id].each do |supplier_id|
      current_user.request_quotes.create(item_ids: params[:request_quote][:item_ids],supplier_id: supplier_id)
    end
    flash[:notice] = "Request successfully sent"
    redirect_to products_url
  end

  def search
    @companys = Company.where("$text"=>{"$search"=>params["key"]}).desc(:created_at).paginate(page: params[:page], per_page: 5)
    render "index"
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(params[:company].keys,attention: [])
  end

end

app/views/companies/_form.html.haml
.row
  .col-md-3.mbtm15
    Company Name
    = text_field_tag("company[name]", client.present?  ? client.name : nil, class: "form-control", required: true)
  .col-md-3.mbtm15{style: "width: 30%;"}
    Attention
    .row
      .col-md-12#field
        = text_field_tag("company[attention][]", nil, class: "attention")
        %button#b1.btn#add-more{:type => "button"} +
.row
  .col-md-3.mbtm15
    Address
    = text_field_tag("company[address]", client.present?  ? client.address : nil, class: "form-control", required: true)
  .col-md-3.mbtm15
    City
    = text_field_tag("company[city]", client.present? ? client.city : nil, class: "form-control", required: true)
.row
  .col-md-3.mbtm15
    State
    = text_field_tag("company[state]", client.present? ? client.state  : nil,class: "form-control", required: true)
  .col-md-3.mbtm15
    Zip
    = text_field_tag("company[zip]", client.present? ? client.zip : nil, class: "form-control", required: true)
.row
  .col-md-3.mbtm15
    Phone
    = phone_field_tag("company[phone]", client.present? ? client.phone : nil, class: "form-control", required: true)
  .col-md-3.mbtm15
    Email
    = email_field_tag("company[email]", client.present? ? client.email : nil, class: "form-control", required: true)
.row{style: "display:none;"}

app/views/companies/create.js.erb
$("#project_client_id").append("<option value=<%=@company.id%>><%=@company.name%></option>");

app/views/companies/edit.html.haml
%section#main-content
  %section.wrapper
    %h2 Edit Client/Supplier
    %section.panel
      %div.panel-body.ptop35
        = form_tag company_path(@company.id), method: :patch do
          .row
            .col-md-3.mbtm15
              = select_tag "company[_type]", options_for_select([["Client","Companies::Client"],["Supplier","Companies::Supplier"]],@company._type),prompt: "Select Client/Supplier", class: "form-control", required: true
          .row
            .col-md-3.mbtm15
              Company Name
              = text_field_tag("company[name]", @company.name, class: "form-control", required: true)
            - if @company.attention.kind_of?(Array)
              .col-md-3.mbtm15{style: "width: 30%;"}
                Attention
                - @company.attention.each_with_index do |val,ind|
                  .row
                    .col-md-12#field
                      = text_field_tag("company[attention][]", val, class: "attention")
                      - if ind == 0
                        %button#b1.btn#add-more{:type => "button"} +
            - else
              .col-md-3.mbtm15{style: "width: 30%;"}
                .row
                  .col-md-12#field
                    = text_field_tag("company[attention][]", @company.attention, class: "attention", placeholder: "Attention")
                    %button#b1.btn#add-more{:type => "button"} +
          .row
            .col-md-3.mbtm15
              Address
              = text_field_tag("company[address]", @company.address, class: "form-control", required: true)
            .col-md-3.mbtm15
              City
              = text_field_tag("company[city]", @company.city, class: "form-control", required: true)
          .row
            .col-md-3.mbtm15
              State
              = text_field_tag("company[state]", @company.state, class: "form-control", required: true)
            .col-md-3.mbtm15
              Zip
              = text_field_tag("company[zip]", @company.zip, class: "form-control", required: true)
          .row
            .col-md-3.mbtm15
              Phone
              = phone_field_tag("company[phone]", @company.phone, class: "form-control", required: true)
            .col-md-3.mbtm15
              Email
              = email_field_tag("company[email]", @company.email, class: "form-control", required: true)
          .row
            .col-md-12
              .actions
                = submit_tag nil,class: "btn btn-primary"

app/views/companies/index.html.haml
%section#main-content.cus
  %section.wrapper
    %div.serch_bg
      #top_menu.nav.search-row.txt-clr
        %ul.nav.top-menu
          %li
            = link_to "Add Client/Supplier", new_company_path,class:'btn'
          %li
            = form_tag(search_companies_path, method: :get) do
              %input.form-control{placeholder: "Search", type: "text", name: "key"}
    %section.panel
      %header.panel-heading.no-border
        Client's/Supplier's
      %table.table.table-bordered
        %thead
          %tr
            %th #
            %th Client/Supplier Name
            %th Type
            %th Action
        %tbody
        - @companys.each_with_index do |company,index|
          %tr
            %td
              #{index+1}
            %td
              #{company.name}
            %td
              #{company._type.split("::").last}
            %td
              .btn-group
                = link_to("", edit_company_path(company.id), class: "btn glyphicon glyphicon-pencil black" )
                = link_to("", company_path(company.id), method: :delete, class: "btn glyphicon glyphicon-trash red verticalLine" )
      .flickr_pagination
        = will_paginate @companys

app/views/companies/new.html.haml
%section#main-content
  %section.wrapper
    %h2 Create Client/Supplier
    %section.panel
      %div.panel-body.ptop35
        = form_tag companies_path, method: :post do
          .row
            .col-md-3.mbtm15
              = select_tag :_type, options_for_select(%w(Client Supplier)),prompt: "Select Client/Supplier", class: "form-control", required: true
          = render 'form',client: nil
          .row
            .col-md-12
              .actions
                = submit_tag nil,class: "btn btn-primary"