config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  get '/dashboard' => 'home#index', as: :dashboard

  resources :projects do
    member do
      get "customer_qoute"
      get "send_quotation"
      post "rfq"
      post "create_order"
    end
    collection do
      post 'request_supplier_qoute'
      get 'search'

    end
  end

  resources :companies do
    collection do
      get "search"
    end
  end
  resources :products do
    collection do
      get 'load_form'
      get 'load_addons'
      get 'prefill_data'
      get "artwork_children"
    end
  end
  resources :orders do
    collection do
      get 'tracking'
      get 'status'
      post 'create_order_tracking'
      get 'search'
    end
    member do
      get "enter_shipment_details"
    end
  end

  get '/users/new'=>"users#new", as: :new_users
  post '/users/create'=>"users#create", as: :users
  get '/project-managers'=>"users#index", as: :project_managers
  delete 'users/:id', to: "users#destroy", as: :destroy_user
  get "users/search", to: "users#search"
  post 'create_request_quote', to: "companies#create_request_quote", as: :create_request_quote

  get '/product_ajax_load', to: 'projects#product_ajax_load'
  get '/quote_request/:id', to: "prices#new_supplier_price", as: :quote_request
  post '/prices', to: "prices#create", as: :prices
  patch '/prices/:id', to: "prices#update", as: :price

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include Mongoid::Paranoia

  has_many :prices

  def details

  end
end

app/models/products/addon.rb
class Products::Addon < Product
  mount_uploader :source, SourceUploader


end

app/models/products/addons/bulb.rb
class Products::Addons::Bulb < Products::Addon

   field :description

  def details
     description
  end

end

app/models/products/addons/container.rb
class Products::Addons::Container < Products::Addon

  field :name

  def details
    name
  end
end

app/models/products/addons/frame.rb
class Products::Addons::Frame < Products::Addon

  field :size
  field :finish
  field :category

end

app/models/products/addons/image.rb
class Products::Addons::Image < Products::Addon

  field :title
  field :artist
  field :width
  field :height

end

app/models/products/addons/shade.rb
class Products::Addons::Shade < Products::Addon

  field :description

   def details
     description
   end
end

app/models/products/artificial_plant.rb
class Products::ArtificialPlant < Product


  field :name
  field :size
  field :fire_rating
  field :container_id


  #need image source field source
  mount_uploader :source, SourceUploader

  def field_names
    %w(plant_name size)
  end

  def addons
    %w(container)
  end

  def number=(arg)
    price = Price.find_by(artline_item_number:arg)
    if price and price.product
      self.name = price.product.name
      self.size = price.product.size
    end
  end

  def container=(arg)
    product= Container.create(arg)
    unless product.errors.any?
      self.container_id = product.id
    else
      errors.add(:container, product.errors.full_messages.join(', '))
    end
  end

  def container
    Container.find(container_id)
  end


  def self.artine_item_numbers
    Price.in(product_id: pluck(:id)).pluck(:artline_item_number)
  end

  def description
    name
  end

  def details
    "#{description} \n size: #{size} \n Container: #{container.name}"
  end
end

app/models/products/artwork.rb
class Products::Artwork < Product


  #field :type
  field :title
  field :width    #image width
  field :height   #image height
  field :supplier_id
  field :moulding_company_id
  field :frame_id
  field :image_id
  field :board_option
  field :acrylic_thickness
  field :matting
  field :mat_size
  field :mat_special_instructions
  field :glazing
  field :glazing_special_instructions
  field :glass_width
  field :glass_height
  field :glass_united_inches
  field :category
  field :frame_size
  field :overall_width
  field :overall_height

   #need image source field source
  mount_uploader :source, SourceUploader

  def field_names
    %w(title artist width height source)
  end

  def addons
    %w(frame)
  end

  def image=(arg)
    image = Image.create(arg)
    unless image.errors.any?
      self.image_id = image.id
      self.title = image.title
      self.width = image.width
      self.height = image.height
    else
      errors.add(:image, product.errors.full_messages.join(', '))
    end
  end

  def supplier=(arg)
    supplier= Supplier.create(arg)
    unless supplier.errors.any?
      self.supplier_id = supplier.id
    else
      errors.add(:supplier, product.errors.full_messages.join(', '))
    end
  end

  def moulding_company=(arg)
    company = MouldingCompany.create(arg)
    unless company.errors.any?
      self.moulding_company_id = company.id
    else
      errors.add(:moulding_company, product.errors.full_messages.join(', '))
    end
  end

  def frame=(arg)
    frame = Frame.create(arg)
    unless frame.errors.any?
      self.frame_id = frame.id
      self.category = frame.category
      self.frame_size = frame.size
    else
      errors.add(:frame, product.errors.full_messages.join(', '))
    end
  end

  def new_board_option=(arg)
    self.board_option = arg[:name]
  end

  def new_acrylic_thickness=(arg)
    self.acrylic_thickness = arg[:name]
  end

  def new_matting=(arg)
    self.matting = arg[:name]
  end

  def supplier
    Supplier.find(supplier_id)
  end

  def moulding_company
    MouldingCompany.find(moulding_company_id)
  end

  def frame
    Frame.find(frame_id)
  end

  def image
    Image.find(image_id)

  end

  def self.artine_item_numbers
    Price.in(product_id: Artwork.pluck(:id)).pluck(:artline_item_number)
  end


  def details
     "Publisher: #{supplier.name}\n Image: #{image["title"]}  Artist: #{image.artist}\n Title: #{title} \n Width: #{width}\n Height: #{height}"
  end

  def glass_united_inches
    self["glass_width"].to_i + self["glass_height"].to_i
  end

end

app/models/products/item.rb
class Products::Item < Product
 belongs_to :category
end

app/models/products/lamp.rb
class Products::Lamp < Product


  field :description
  field :size
  field :shade_id, type: BSON::ObjectId
  field :bulb_id, type: BSON::ObjectId

  #need image source field source
  mount_uploader :source, SourceUploader

  def field_names
    %w(description size)
  end

  def addons
    %w(shade bulb)
  end

  def number=(arg)
    price = Price.find_by(artline_item_number:arg)
    if price and price.product
      self.description = price.product.description
      self.size = price.product.size
    end
  end

  def shade=(arg)
    product= Shade.create(arg)
    unless product.errors.any?
      self.shade_id = product.id
    else
      errors.add(:shade, product.errors.full_messages.join(', '))
    end
  end

  def bulb=(arg)
    product= Bulb.create(arg)
    unless product.errors.any?
      self.bulb_id = product.id
    else
      errors.add(:bulb, product.errors.full_messages.join(', '))
    end
  end

  def shade
    Shade.find(shade_id)
  end

  def bulb
    Bulb.find(bulb_id)
  end

  def details
    "#{description} \n size: #{size} \n Shade: #{shade.description}\n Bulb: #{bulb.description}"
  end

  def self.artine_item_numbers
    Price.in(product_id: only(:id).all.map(&:id)).only(:artline_item_number).map(&:artline_item_number)
  end

end

app/models/products/mirror.rb
class Products::Mirror < Product

  field :bevel
  field :bevel_size
  field :bevel_special_instructions
  field :glazing
  field :glazing_special_instructions
  field :glass_width
  field :glass_height
  field :frame_category
  field :frame_size
  field :united_inches
  field :moulding_company_id
  field :frame_id
  field :overall_width
  field :overall_height

  mount_uploader :source, SourceUploader

  def field_names
    %w( )
  end

  def addons
    %w(frame)
  end

  def moulding_company=(arg)
    company = MouldingCompany.create(arg)
    unless company.errors.any?
      self.moulding_company_id = company.id
    else
      errors.add(:moulding_company, product.errors.full_messages.join(', '))
    end
  end

  def frame=(arg)
    frame = Frame.create(arg)
    unless frame.errors.any?
      self.frame_id = frame.id
      self.frame_category = frame.category
      self.frame_size = frame.size
    else
      errors.add(:frame, product.errors.full_messages.join(', '))
    end
  end

  def moulding_company
    MouldingCompany.find(moulding_company_id)
  end

  def frame
    Frame.find(frame_id)
  end

  def size
    0
  end

  def united_inches
    overall_width.to_f + overall_height.to_f
  end

  def description
    ""
  end

  def details
    "Bevel: #{bevel},  Bevel size: #{bevel_size}\n Glazing: #{glazing} \n Glass width: #{glass_width},  Glass height: #{glass_height}\n Frame: #{frame.finish},  Frame size: #{frame_size}\n Moulding company: #{moulding_company.name}\n Overall width: #{overall_width},  Overall height: #{overall_height}"
  end

end

app/models/products/other.rb
class Products::Other < Product

  field :tag
  field :quantity
  field :description
  field :special_instructions

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show,:edit, :update, :destroy]

  def index
    @products = Product.order_by(created_at: "desc").paginate(page: params[:page], per_page: 5)
  end

  def new
    @type = params[:type]
    # @product = Product.new
  end

  def create
    @product = eval(params[:item_type]).create(product_params)
    unless @product.errors.any?
      redirect_to product_url(@product)
    else
      render new
    end
  end

  def show
    #@suppliers = Supplier.all
    if Categories.keys.include?@product._type.split("::").last
      @quoted = Price.where(product_id: @product.id)
      @non_quoted_supplier = Companies::Supplier.nin(id: @quoted.pluck(:supplier_id))
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      flash[:noice] = "Successfully Updated"
      redirect_to product_url(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    flash[:notice]= "Item successfully deleted"
    redirect_to products_url
  end


  def load_form
    @product = eval(params[:item]).new
  end

  def load_addons

  end

  def prefill_data
    quote = Price.where(artline_item_number: params[:artline_number]).first unless params[:addon]
    product = params[:addon] ? Product.where(id: params[:artline_number]).first : quote.product
    render json: case product.class.to_s.split("::").last
                   when 'Lamp'
                     {"shade_id"=> product.shade_id.to_s, "bulb_id"=> product.bulb_id.to_s}
                   when 'ArtificialPlant'
                     {"fire_rating"=>product.fire_rating, "container_id"=>product.container_id.to_s}
                   when 'Frame'
                     product.attributes.slice("category", "size")
                   when 'Image'
                     product.attributes.slice("title", "width", "height")
                   else
                     {}
                 end

  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit!
  end

end

app/views/products/artwork_children.js.erb
$('.selected_item').empty().append("<div class='row'><div class='col-md-3 mbtm15'><%=j select_tag("child_product", options_for_select(Childrens[params[:item]].to_a.map(&:reverse)),prompt: "Select Product" , onchange: "getArtworkForm(this)", class: "form-control", required: true )%></div></div><div class='row'><div class='col-md-12 artwork_form'></div></div>")

app/views/products/edit.html.haml
%section#main-content
  %section.wrapper
    %h1 Edit Item
    %section.panel
      %div.panel-body.ptop35
        - product = @product._type.split("::").last
        - if product.eql?("Artwork")
          = render  "/products/forms/artwork/#{@product.artwork_type.downcase}"
        - else
          = render  "/products/forms/#{product.downcase}"

= javascript_include_tag 'product', 'data-turbolinks-track' => true

app/views/products/index.html.haml
%section#main-content.cus
  %section.wrapper
    %div.serch_bg
      #top_menu.nav.search-row.txt-clr
        %ul.nav.top-menu
          %li
            = link_to "Add addon", new_product_path(type: "addon"),class:'btn'
          %li
            = link_to "Add Item", new_product_path(type: "item"),class:'btn'
          %li
            -#%form.navbar-form
              %input.form-control{:placeholder => "Search", :type => "text"}
    %section.panel
      %header.panel-heading.no-border
        Item's
      %table.table.table-bordered
        %thead
          %tr
            %th #
            %th Type
            %th Action
        %tbody
        - @products.each_with_index do |product,index|
          %tr
            %td
              #{index+1}
            %td
              - item = product._type.split("::").last
              = link_to("#{item.eql?("Artwork") ? product.artwork_type : item}", product_path(product.id) )
              - if product.has_attribute?(:source) && product.source.present?
                = image_tag(product.source, class: "product_mini_img" )
            %td
              .btn-group
                = link_to("", edit_product_path(product.id), class: "btn glyphicon glyphicon-pencil black" )
                = link_to("", product_path(product.id), method: :delete, class: "btn glyphicon glyphicon-trash red verticalLine" )
      .flickr_pagination
        = will_paginate @products

app/views/products/load_addons.js.erb
$("."+"<%=params["class_name"]%>").append("<%= j render(:partial => '/products/forms/new_addons/'+ params["class_name"].downcase ) %>");

app/views/products/load_form.js.erb
<%unless params["class_name"].blank?%>
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).html("<%= j render(:partial => '/projects/forms/new_item/'+ params["item"].downcase ) %>");
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).prev('.row').remove();
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).nextAll(".replaceable:eq(0)").remove();
   <%if params["class_name"].eql?("frame")%>
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).find("input[id$='frame_size']:eq(0)").trigger('change');
   <%elsif params["class_name"].eql?("image") %>
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).find("input[id$='new_image_width']:eq(0)").trigger('change');
    $("."+"<%=params["class_name"]%>").eq(<%=params["index"].to_i%>).find("input[id$='new_image_height']:eq(0)").trigger('change');
   <%end%>
<%else%>
    <% if params[:item].eql?("Artwork") %>
      $('.artwork_form').empty().append("<%= j render(:partial => '/products/forms/artwork/'+ params[:artwork_children].downcase ) %>");
    <% else  %>
      $('.selected_item').empty().append("<%= j render(:partial => '/products/forms/'+ params[:item].downcase ) %>");
    <%end%>
<%end%>

app/views/products/new.html.haml
%section#main-content
  %section.wrapper
    %h1 Add Item
    %section.panel
      %div.panel-body.ptop35
        - if @type.eql?("addon")
          .row
            .col-md-3.mbtm15
              = select_tag("product_type", options_for_select(Addons.to_a.map(&:reverse)),include_blank: "Addon Type" , class: "form-control")
        - elsif @type.eql?("item")
          .row
            .col-md-3.mbtm15
              = select_tag("product_type", options_for_select(Categories.to_a.map(&:reverse)),include_blank: "Item Type" , class: "form-control")
        .row
          .col-md-12.selected_item

= javascript_include_tag 'product', 'data-turbolinks-track' => true

app/views/products/price.html.haml
%h1 Product Price
%section.panel
  .panel-body.ptop35
    .row
      .col-md-3
        Item number
      .col-md-3
        Name
      .col-md-3
        Supplier item number
      .col-md-3
        Price
    %hr
    =form_tag update_product_price_path(@product.id), method: :post do
      .row
        .col-md-3
          = "#{@product.id}"
        .col-md-3
          = "#{@product._type.split("::").last}"
        .col-md-3
          = text_field_tag("product[supplier_item_number]", nil, class: "form-control",  required: true)
        .col-md-3
          = text_field_tag("product[supplier_cost]",nil, class: "form-control",  required: true)
      %hr
      .row
        .col-md-12
          = submit_tag("SAVE", class: "btn btn-success")

app/views/products/show.html.haml
%section#main-content.cus
  %section.wrapper
    %section.panel
      %header.panel-heading.no-border
        Item
      %table.table.table-bordered
        %thead
          %tr
            %th Type
            %th Action
        %tbody
          %tr
            %td
              - item = @product._type.split("::").last
              = item.eql?("Artwork") ? @product.artwork_type : item
              - if @product.has_attribute?(:source) && @product.source.present?
                = image_tag(@product.source, class: "product_mini_img" )
            %td
              .btn-group
                = link_to("", edit_product_path(@product.id), class: "btn glyphicon glyphicon-pencil black")
                = link_to("", product_path(@product.id), method: :delete, class: "btn glyphicon glyphicon-trash red verticalLine")
    - if Categories.keys.include?@product._type.split("::").last
      .col-md-6
        %header.panel-heading.no-border
          Quoted supplier's list
        %table.table.table-bordered.panel
          %thead
            %tr
              %th Supplier name
              %th Price
          %tbody
            - @quoted.each do |q|
              %tr
                %td
                  = q.companies_supplier.name
                %td
                  .row{style: "display: none;"}
                    .col-md-8{style: "padding-right: 0px"}
                      = hidden_field_tag "product_id", q.product_id
                      = hidden_field_tag "supplier_id", q.supplier_id
                      = number_field_tag("price", nil, class: "form-control price_border",  required: true,autofocus: true)
                    %button.btn-success{style: "padding: 5px;",onclick:  "update_price(this)"}
                      .glyphicon.glyphicon-ok
                  .price_field
                    %span.price
                      = q.supplier_cost
                    &nbsp
                    %button.glyphicon.glyphicon-pencil.black.edit_product_price{onclick: "edit_price(this)"}

      - if @non_quoted_supplier.count > 0
        .col-md-6
          %header.panel-heading.no-border
            Add Quote
          .panel
            =form_tag prices_path, method: :post,style: "padding: 15px;" do
              = hidden_field_tag "created_by_admin", "yes"
              = hidden_field_tag "products[][product_id]", @product.id
              .row.mbtm15
                .col-md-4
                  Name :
                  %b
                    = @product._type.split("::").last
              .row.mbtm15
                .col-md-6
                  Supplier
                  = select_tag("products[][supplier_id]", options_for_select(@non_quoted_supplier.map{|c|[c.name, c.id]}),prompt: "Supplier" , class: "form-control", required: true)
                .col-md-6
                  Supplier item number
                  = text_field_tag("products[][supplier_item_number]", nil, class: "form-control",  required: true)
              .row.mbtm15
                .col-md-6
                  Each Cost
                  = number_field_tag("products[][supplier_cost]", nil, class: "form-control",min: 0,  required: true)
              .row.mbtm15
                .col-md-12
                  Additional Note(optional)
                  = text_area_tag("products[][supplier_note]", nil, class: "form-control")
              = submit_tag("Submit", class: "btn btn-success")